export const metadata = {
  title: "Product!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <>
        {children}
        </>
  );
}